project:
  type: book
  output-dir: docs/

book:
  title: "Econometria Espacial aplicada com R"
  author: 
    - "Raphael Saldanha"
    - "Eduardo Almeida"
  date: today
  chapters:
    - index.qmd
    - intro_r.qmd
    - aede.qmd
    - matrizes.qmd
    - modelos_corte_transversal.qmd
    - gwr.qmd
    - modelos_painel.qmd
    - references.qmd
  appendices: 
    - importar_matriz.qmd
    - probit_espacial.qmd

lang: pt

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual

